### ISSUE TITLE
Is this library usable?

### ISSUE THREAD

**Issue by darmie** [luboslenco/haxeduktape#1]
Hi @luboslenco , I am interested in using this library. Does it work?

**Comment by luboslenco** [comment]
Hello @darmie!

I recall that I got `DukContext.evalString()` to actually work, but that is pretty much it.

Haxe framework Kha now makes it possible to execute JavaScript (and WebAssembly should be doable too) on C++ targets using [Krom](https://github.com/Kode/Krom) which embeds V8, so that is where I put my efforts now.

**Comment by darmie** [comment]
Oh thanks. I will try Krom.
